CREATE TABLE `trading_all` (
  `order_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ordertime` datetime DEFAULT current_timestamp(),
  `strategy_name` varchar(255) DEFAULT NULL,
  `broker` varchar(255) DEFAULT NULL,
  `account_id` int(11) DEFAULT NULL,
  `mode` enum('PAPER','PROD') DEFAULT 'PAPER',
  `equity` decimal(12,2) DEFAULT NULL,
  `underlying` varchar(50) DEFAULT NULL,
  `expiration` varchar(8) DEFAULT NULL,
  `strike` decimal(10,2) DEFAULT NULL,
  `right` varchar(1) DEFAULT NULL,
  `leg` decimal(10,0) DEFAULT NULL,
  `legtime` time DEFAULT NULL,
  `ticker` varchar(64) DEFAULT NULL,
  `side` varchar(10) DEFAULT NULL,
  `lots` int(11) DEFAULT NULL,
  `bid` decimal(10,2) DEFAULT NULL,
  `ask` decimal(10,2) DEFAULT NULL,
  `ltp` decimal(10,2) DEFAULT NULL,
  `net` decimal(10,2) DEFAULT NULL,
  `buytime` datetime DEFAULT NULL,
  `selltime` datetime DEFAULT NULL,
  `buytriggerprice` decimal(10,2) DEFAULT NULL,
  `selltriggerprice` decimal(10,2) DEFAULT NULL,
  `buy_slippage_pts` decimal(10,2) DEFAULT NULL,
  `sell_slippage_pts` decimal(10,2) DEFAULT NULL,
  `buy_slippage_value` decimal(10,2) DEFAULT NULL,
  `sell_slippage_value` decimal(10,2) DEFAULT NULL,
  `buyprice` decimal(10,2) DEFAULT 0.00,
  `sellprice` decimal(10,2) DEFAULT 0.00,
  `mtm` decimal(10,2) DEFAULT 0.00,
  `realized` decimal(10,2) DEFAULT 0.00,
  `total_pnl` decimal(10,2) DEFAULT 0.00,
  `quantity` int(11) DEFAULT 0,
  `quantity_filled` int(11) DEFAULT 0,
  `quantity_exited` int(11) DEFAULT 0,
  `remarks` varchar(128) DEFAULT NULL,
  `last_updated` datetime(3) DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  `last_updated_date` date GENERATED ALWAYS AS (cast(`last_updated` as date)) VIRTUAL,
  `order_date` date GENERATED ALWAYS AS (cast(`ordertime` as date)) VIRTUAL,
  PRIMARY KEY (`order_id`),
  KEY `ix_broker_account_id_trading_all` (`order_date`,`broker`,`account_id`),
  KEY `ix_strategy_name_order_id_trading_all` (`order_date`,`strategy_name`,`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=519 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
